// Code generated by MockGen. DO NOT EDIT.
// Source: wallet.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"
	entity "yyq1025/balance-backend/internal/entity"

	gomock "github.com/golang/mock/gomock"
)

// MockWalletUseCase is a mock of WalletUseCase interface.
type MockWalletUseCase struct {
	ctrl     *gomock.Controller
	recorder *MockWalletUseCaseMockRecorder
}

// MockWalletUseCaseMockRecorder is the mock recorder for MockWalletUseCase.
type MockWalletUseCaseMockRecorder struct {
	mock *MockWalletUseCase
}

// NewMockWalletUseCase creates a new mock instance.
func NewMockWalletUseCase(ctrl *gomock.Controller) *MockWalletUseCase {
	mock := &MockWalletUseCase{ctrl: ctrl}
	mock.recorder = &MockWalletUseCaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockWalletUseCase) EXPECT() *MockWalletUseCaseMockRecorder {
	return m.recorder
}

// AddOne mocks base method.
func (m *MockWalletUseCase) AddOne(arg0 context.Context, arg1 *entity.Wallet) (entity.Balance, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddOne", arg0, arg1)
	ret0, _ := ret[0].(entity.Balance)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AddOne indicates an expected call of AddOne.
func (mr *MockWalletUseCaseMockRecorder) AddOne(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddOne", reflect.TypeOf((*MockWalletUseCase)(nil).AddOne), arg0, arg1)
}

// DeleteOne mocks base method.
func (m *MockWalletUseCase) DeleteOne(arg0 context.Context, arg1 *entity.Wallet) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteOne", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteOne indicates an expected call of DeleteOne.
func (mr *MockWalletUseCaseMockRecorder) DeleteOne(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteOne", reflect.TypeOf((*MockWalletUseCase)(nil).DeleteOne), arg0, arg1)
}

// GetManyWithPagination mocks base method.
func (m *MockWalletUseCase) GetManyWithPagination(arg0 context.Context, arg1 *entity.Wallet, arg2 *entity.Pagination) ([]entity.Balance, *entity.Pagination, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetManyWithPagination", arg0, arg1, arg2)
	ret0, _ := ret[0].([]entity.Balance)
	ret1, _ := ret[1].(*entity.Pagination)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetManyWithPagination indicates an expected call of GetManyWithPagination.
func (mr *MockWalletUseCaseMockRecorder) GetManyWithPagination(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetManyWithPagination", reflect.TypeOf((*MockWalletUseCase)(nil).GetManyWithPagination), arg0, arg1, arg2)
}

// GetOne mocks base method.
func (m *MockWalletUseCase) GetOne(arg0 context.Context, arg1 *entity.Wallet) (entity.Balance, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetOne", arg0, arg1)
	ret0, _ := ret[0].(entity.Balance)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetOne indicates an expected call of GetOne.
func (mr *MockWalletUseCaseMockRecorder) GetOne(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetOne", reflect.TypeOf((*MockWalletUseCase)(nil).GetOne), arg0, arg1)
}

// MockWalletRepository is a mock of WalletRepository interface.
type MockWalletRepository struct {
	ctrl     *gomock.Controller
	recorder *MockWalletRepositoryMockRecorder
}

// MockWalletRepositoryMockRecorder is the mock recorder for MockWalletRepository.
type MockWalletRepositoryMockRecorder struct {
	mock *MockWalletRepository
}

// NewMockWalletRepository creates a new mock instance.
func NewMockWalletRepository(ctrl *gomock.Controller) *MockWalletRepository {
	mock := &MockWalletRepository{ctrl: ctrl}
	mock.recorder = &MockWalletRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockWalletRepository) EXPECT() *MockWalletRepositoryMockRecorder {
	return m.recorder
}

// AddOne mocks base method.
func (m *MockWalletRepository) AddOne(ctx context.Context, wallet *entity.Wallet) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddOne", ctx, wallet)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddOne indicates an expected call of AddOne.
func (mr *MockWalletRepositoryMockRecorder) AddOne(ctx, wallet interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddOne", reflect.TypeOf((*MockWalletRepository)(nil).AddOne), ctx, wallet)
}

// DeleteOne mocks base method.
func (m *MockWalletRepository) DeleteOne(ctx context.Context, condition *entity.Wallet) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteOne", ctx, condition)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteOne indicates an expected call of DeleteOne.
func (mr *MockWalletRepositoryMockRecorder) DeleteOne(ctx, condition interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteOne", reflect.TypeOf((*MockWalletRepository)(nil).DeleteOne), ctx, condition)
}

// GetManyWithPagination mocks base method.
func (m *MockWalletRepository) GetManyWithPagination(ctx context.Context, condition *entity.Wallet, wallet *[]entity.Wallet, p *entity.Pagination) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetManyWithPagination", ctx, condition, wallet, p)
	ret0, _ := ret[0].(error)
	return ret0
}

// GetManyWithPagination indicates an expected call of GetManyWithPagination.
func (mr *MockWalletRepositoryMockRecorder) GetManyWithPagination(ctx, condition, wallet, p interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetManyWithPagination", reflect.TypeOf((*MockWalletRepository)(nil).GetManyWithPagination), ctx, condition, wallet, p)
}

// GetOne mocks base method.
func (m *MockWalletRepository) GetOne(ctx context.Context, condition, wallet *entity.Wallet) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetOne", ctx, condition, wallet)
	ret0, _ := ret[0].(error)
	return ret0
}

// GetOne indicates an expected call of GetOne.
func (mr *MockWalletRepositoryMockRecorder) GetOne(ctx, condition, wallet interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetOne", reflect.TypeOf((*MockWalletRepository)(nil).GetOne), ctx, condition, wallet)
}
