version: '3.9'
services:
  redis:
    image: mcr.microsoft.com/oss/bitnami/redis:6.0.8
    container_name: redis
    environment: 
      - ALLOW_EMPTY_PASSWORD=yes
    restart: always
    ports:
      - 6379:6379

  api:
    image: yyq1025/balance-backend:latest
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - redis
    env_file:
      - ./.env
