name: Go CI

on:
  push:
    branches:
      - main
    paths-ignore:
      - "**/*.md"
  pull_request:
    branches:
      - main
    paths-ignore:
      - "**/*.md"
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version-file: "go.mod"
          cache: true
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v6
        with:
          version: latest

  test:
    runs-on: ubuntu-latest

    services:
      sql-server:
        image: mcr.microsoft.com/mssql/server
        env:
          ACCEPT_EULA: Y
          MSSQL_SA_PASSWORD: Sa_password
          MSSQL_PID: Express
        options: >-
          --health-cmd "/opt/mssql-tools/bin/sqlcmd -U sa -P Sa_password -Q 'select 1'"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 1433:1433

      redis:
        image: redis
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 6379:6379

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 2
      - uses: actions/setup-go@v5
        with:
          go-version-file: "go.mod"
          cache: true
      - name: Run SQL scripts
        run: |
          sqlcmd -S localhost -U sa -P Sa_password -d master -i ./sql/schema.sql
          sqlcmd -S localhost -U sa -P Sa_password -d master -i ./sql/test_data.sql

      - name: Run coverage
        env:
          AUTH0_DOMAIN: test
          AUTH0_AUDIENCE: test
        run: go test -race -coverprofile=coverage.txt -covermode=atomic ./internal/...
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: "go.mod"
          cache: true

      - name: Build
        run: go build -v ./...
