# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - balance-backend

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to registry
      uses: docker/login-action@v1
      with:
        registry: https://testbalance.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_841572c671d1446c81224aa145fa6193 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_e23f311c7ce44fd0bce8d6c15af06853 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: testbalance.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_841572c671d1446c81224aa145fa6193 }}/balance:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'balance-backend'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_70ab4d621c744e069f199f3fa6841640 }}
        images: 'testbalance.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_841572c671d1446c81224aa145fa6193 }}/balance:${{ github.sha }}'